### ISSUE TITLE
1.1 Roadmap

### ISSUE THREAD

**Issue by democloid** [democloid/picoTracker#10]
Objective: No new features, fix known issues with 1.0. Add functionality that should have been there in 1.0

- [ ] Fix sample import dialog
  - [x] Audio corruption after import
  - [x] Audio corruption after listen
  - [ ] Directory listing limitations (currently capped at 25 entries due to memory issues)
- [ ] Add MIDI In
- [ ] Test and potentially fix Midi Out (pretty confident it's not correct)
- [ ] Improve battery life (exploratory)
  - [ ] CPU frequency up only when playing
- [ ] Fix "Compact Instruments"

**Comment by democloid** [comment]
Tracking this via milestones
