### ISSUE TITLE
1.2 Roadmap

### ISSUE THREAD

**Issue by democloid** [democloid/picoTracker#11]
Objective: new features

- [ ] New instruments (synths)
- [ ] Show in sample import dialog if a certain sample is already imported (and don't re-import)
- [ ] Fix sample import "Listen" option to play at the right sample rate

**Comment by maks** [comment]
I thought it might be good to break these out into their own issues and not sure if you know as Github has the "Milestone" functionality so this could be replaced by one which each of the separate issues are assigned to - hope thats ok and I closed this one.
